### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by ParisMolver** [mormegil-cz/btsnoozdecoder#1]
```
        private static ushort SwapBytes(ushort x) => (ushort) ((ushort) ((x & 0xff) << 8) | ((x >> 8) & 0xff));

        private static uint SwapBytes(uint x) =>
            ((x & 0x000000ff) << 24) +
            ((x & 0x0000ff00) << 8) +
            ((x & 0x00ff0000) >> 8) +
            ((x & 0xff000000) >> 24);
            
```
  The last block of code can't compile. Using 
`
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc Program.cs`

command to build and getting the following errors
```

Program.cs(175,51): error CS1002: ; expected
Program.cs(175,61): error CS1519: Invalid token ')' in class, struct, or interface member declaration
Program.cs(175,71): error CS1519: Invalid token ')' in class, struct, or interface member declaration
Program.cs(175,77): error CS1519: Invalid token '&' in class, struct, or interface member declaration
Program.cs(175,97): error CS1519: Invalid token '>' in class, struct, or interface member declaration
Program.cs(177,47): error CS1002: ; expected
Program.cs(178,17): error CS1519: Invalid token '&' in class, struct, or interface member declaration
Program.cs(179,17): error CS1519: Invalid token '&' in class, struct, or interface member declaration
Program.cs(180,17): error CS1519: Invalid token '&' in class, struct, or interface member declaration
Program.cs(181,17): error CS1519: Invalid token '&' in class, struct, or interface member declaration
```

**Comment by mormegil-cz** [comment]
The tool is written in C# 8, which is not supported by the old C# compiler from .NET Framework 4 (and if I try to run the compiler this way, it even explicitly warns me that _“This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240 ”_).

You should download a current version of .NET (see e.g. https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60), then you can build the project using `dotnet build` (or even run it directly using `dotnet run`).

Or, it should not be too difficult to modify the code to use only C# 5 constructions, I guess. The only changes necessary would be replacing the two arrow functions with plain old `{ return ... }` and replacing the `using var ...` statements with `using (var ...) { ... }`, I think.
